#rest:
#    auth-open: true #jwt鉴权机制是否开启(true或者false)
#    sign-open: true #签名机制是否开启(true或false)

jwt:
    header: Authorization   #http请求头所需要的字段
    secret: mySecret        #jwt秘钥
    expiration: 604800      #7天 单位:秒
    auth-path: auth         #认证请求的路径
    md5-key: randomKey      #md5加密混淆key

# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8099